name: Build and test Clojure

on: [push]

jobs:

  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21.0.1'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.11.1.1155  # Clojure CLI based on tools.deps
          lein: 2.9.10     # Leiningen
          
          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up xvfb
      #   run: |
      #     sudo apt-get install xvfb libxrender1 libxtst6 libxi6
      #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      # - name: Run sketch
      #   run: |
      #     CI_RUN=true DISPLAY=':99.0' lein run pillars
      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@afc83dbbf4e7e32e04649e29dbf30668d30e9e3e
        with:
          version: '2023.03.17'
      - name: Lint
        run: |
          clj-kondo --fail-level error --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

      - name: Run tests
        run: |
          clojure -X:test
