name: Build pillars

on: [push]

jobs:

  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.10.3.986 # Clojure CLI based on tools.deps
          lein: 2.9.8     # Leiningen
          
          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: CI_RUN=true lein run
          working-directory: ./pillars
          # options: #optional
      # - name: Set up xvfb
      #   run: |
      #     sudo apt-get install xvfb libxrender1 libxtst6 libxi6
      #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      #     cd pillars
      #     CI_RUN=true DISPLAY=':99.0' lein run
