name: Build and test Clojure

on: [push]

jobs:

  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.11.1.1155  # Clojure CLI based on tools.deps
          lein: 2.9.10     # Leiningen
          
          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up xvfb
      #   run: |
      #     sudo apt-get install xvfb libxrender1 libxtst6 libxi6
      #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      # - name: Run sketch
      #   run: |
      #     CI_RUN=true DISPLAY=':99.0' lein run pillars
      - name: Lint
        run: |
          clojure -Sdeps '{:deps {clj-kondo/clj-kondo {:mvn/version "2023.01.20"}}}' -M -m clj-kondo.main --fail-level error --lint src

      - name: Run tests
        run: |
          lein test
